
CREATE TABLE NUQABA(
    NAQIB_ID INTEGER CONSTRAINT NUQABA_NAQIB_ID_PK PRIMARY KEY,
    NAQIB_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL CONSTRAINT NUQABA_EMAIL_UK UNIQUE,
    HASH_PASSWORD VARCHAR(50) NOT NULL,
    USRAH_ID INTEGER , 
    CONSTRAINT NUQABA_USRAH_ID_FK FOREIGN KEY(USRAH_ID) REFERENCES USRAH(USRAH_ID)
)

CREATE TABLE USRAH(
    USRAH_ID INTEGER CONSTRAINT USRAH_USRAH_ID_PK PRIMARY KEY,
    USRAH_NAME VARCHAR(50)
)

CREATE TABLE MEMBERS(
    MEMBERS_ID INTEGER CONSTRAINT MEMBERS_MEMBERS_ID_PK PRIMARY KEY,
    MEMBERS_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL,
    USRAH_ID INTEGER,
    CONSTRAINT MEMBERS_USRAH_ID_FK FOREIGN KEY(USRAH_ID) REFERENCES USRAH(USRAH_ID)
)

CREATE TABLE SESSIONS(
    SESSIONS_ID INTEGER  PRIMARY KEY ,
    SESSION_NAME VARCHAR(100),
    SESSION_DATE DATE,
    USRAH_ID INTEGER NOT NULL,
    CONSTRAINT SESSIONS_USRAH_ID_FK FOREIGN KEY(USRAH_ID) REFERENCES USRAH(USRAH_ID)
)

CREATE TABLE ATTENDANCE(
    SESSIONS_ID INTEGER,
    MEMBERS_ID INTEGER,
    CONSTRAINT ATTEND_SEID_MEMID_PK PRIMARY KEY(SESSIONS_ID , MEMBERS_ID),
    CONSTRAINT ATTENDANCE_SESSIONS_ID_FK FOREIGN KEY(SESSIONS_ID) REFERENCES SESSIONS(SESSIONS_ID) ON DELETE CASCADE,
    CONSTRAINT ATTENDANCE_MEMBERS_ID_FK FOREIGN KEY(MEMBERS_ID) REFERENCES MEMBERS(MEMBERS_ID) ON DELETE CASCADE
)

SELECT (
    (
        SELECT COUNT(*)
        FROM ATTENDANCE a 
        JOIN SESSIONS s ON a.usrah_id = s.usrah_id 
        WHERE a.MEMBERS_ID = 100 AND s.USRAH_ID = 200
    )/
    (
        SELECT COUNT(*)
        FROM SESSIONS
        WHERE USRAH_ID = 200
    )
) * 100 AS attendence_percentage;